apiVersion: v1
kind: ConfigMap
metadata:
  name: 1platform-config
  namespace: 1platform
  labels:
    app.kubernetes.io/part-of: 1platform
data:
  NODE_ENV: production
  LOG_LEVEL: info
  WEB_URL: http://1platform-web.1platform.svc.cluster.local
  API_URL: http://1platform-api.1platform.svc.cluster.local:3001
  # Override per overlay (staging / production)
  CORS_ORIGIN: https://app.1platform.internal
