apiVersion: v1
kind: Service
metadata:
  name: 1platform-web
  namespace: 1platform
  labels:
    app.kubernetes.io/name: 1platform-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: 1platform
spec:
  selector:
    app.kubernetes.io/name: 1platform-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
